### PR TITLE
request for review, README.md file and newfeature branch created

### PR DESCRIPTION
**Pull request by mercymugambi**
- Created the index file with class heading in the body.
- Created the test.md suppossed to be ignored.
- Created CSS file containing the heading class color styling.

### CODE REVIEW

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi @mercymugambi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
- [ ] I cannot leave comment there so I am leaving it here. Please implement it
- [ ] I would suggest you please fill the every header in your README file. Here is the [Link](https://github.com/microverseinc/readme-template). Please add the project name and description, key feature, Author, Also please Fix the MIT license in your README file. Every header should be present in your README file. Also remove the Microverse logo, if possible you can use your logo if you want.
- [ ] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). As this is Hello-microverse project you can name this branch `hello_microverse`. please checkout to the new branch and past the link of your old pr to the new pull request.
- [ ] Also I would suggest please rename the title  of your Pull request and make it more descriptive like Hello-Microverse.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mercymugambi** [comment]
Requested changes have been implemented as below.

- Create a new feature branch.
- update README file with heading and descriptive contents.
- Rename pull request title to hello-microverse

**Comment by mercymugambi** [comment]
Requested changes have been implemented as below.

Create a new feature branch.
update README file with heading and descriptive contents and add license to readme.md.
Rename pull request title to [request for review, README.md file and newfeature branch created]

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi  @mercymugambi ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

you-are-near

## Highlights ✔️

- [x] No linter errors. 💯
- [x] Good Setup configuration files and folders

 ## Required Changes ♻️

### I cannot leave a comment there so I am leaving it here. Please implement it 😊

- [x] Kindly 😊 as stated by the previous reviewer use [the Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌
- [x] you did a great job 😃 at adding the MIT LICENCE, but I see that when clicking on the link to open the page of LICENCE I see that it is redirecting me to the page not found, so please 😊 try to put the correct link for the MIT LICENCE to let anyone when clicking on the link of LICENCE redirect him/her to the page of the LICENCE 💯
- [x]   As stated by the previous reviewer kindly 😊 Branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). As this is a Hello-microverse project you can name this branch hello_microverse, so kindly try to rename the name of branch as you see here as main, so it may conflict with the name of master. please checkout to the new branch and paste the link of your old pr to the new pull request.
- [x] As stated by the previous reviewer kindly Also I would suggest please rename the title of your Pull request and making it more descriptive like Hello-Microverse.



## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mercymugambi** [comment]
Hello Reviewer!

1. I have managed to work on all issues, However the last issue addressed ("As stated by the previous reviewer kindly Also I would suggest please rename the title of your Pull request and making it more descriptive like Hello-Microverse.") I don't find it relevant. Please consider the title used as it corresponds to guidlines. 

2. Besides that, this request was opened on main branch though i managed to create a new "heading-feature" as it meets the rules, however the pull request will not allow the renaming unless the issue is closed. Please check my "heading-feature branch" and consider it for this submission.

**Review by RaoAkif — APPROVED** [review]
## STATUS: APPROVED 🎉🎉🎉

#### Hi @mercymugambi, You have done a lot of work on this project. Keep doing hard work. It would surely pay off.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

approve-image

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
